import * as z from "zod";

export const ClothingItem = z.object({
  name: z.string().min(2, "Name must be 2 characters or longer.").trim(),
  size: z.enum(["XS", "S", "M", "L", "XL", "XXL", "XXXL"]),
  category: z.enum([
    "t-shirt",
    "shirt",
    "sweater",
    "sweatshirt",
    "hoodie",
    "jacket",
    "coat",
    "jeans",
    "pants",
    "shorts",
    "sweatpants",
    "dress",
    "skirt",
    "activewear",
    "underwear",
    "sleepwear",
    "swimwear",
    "sneakers",
    "boots",
    "sandals",
    "heels",
    "hat",
    "bag",
    "belt",
    "sunglasses",
    "jewelry",
  ]),
  brand: z.string().min(1).max(20).trim(),
  price: z.number().positive(),
  likesCount: z.number().default(0).optional(),
});
